server:
  port: 8080
  context-path: /mission

spring:
  #数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: qwer1234
    url: jdbc:mysql://127.0.0.1:3306/mission?characterEncoding=utf-8&useSSL=false

    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM t_user
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true

#MyBatis配置
mybatis:
  type-aliases-package: cn.zmhappy.missiondemo.db.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30